name: 检查本地路径

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  check-local-paths:
    runs-on: ubuntu-latest

    steps:
      - name: 检查本地路径
        uses: DuckDuckStudio/Check_Locale_Paths@2f3264da0b9bc5799380851283c7edb1e1ebfe86 # 3.0.0
